; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 5
; RUN: opt < %s -passes=instcombine -S | FileCheck %s

define void @_ZN9btBvhTree15_build_sub_treeER18GIM_BVH_DATA_ARRAYii(ptr %this, i32 %0) {
; CHECK-LABEL: define void @_ZN9btBvhTree15_build_sub_treeER18GIM_BVH_DATA_ARRAYii(
; CHECK-SAME: ptr [[THIS:%.*]], i32 [[TMP0:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[SUB14_NEG:%.*]] = add i32 [[TMP0]], -1, !dbg [[DBG4:![0-9]+]]
; CHECK-NEXT:    store i32 [[SUB14_NEG]], ptr [[THIS]], align 4
; CHECK-NEXT:    ret void
;
entry:
  %sub14 = sub i32 1, %0, !dbg !4
  %sub.i = sub i32 0, %sub14
  store i32 %sub.i, ptr %this, align 4
  ret void
}

!llvm.dbg.cu = !{!0}
!llvm.module.flags = !{!3}

!0 = distinct !DICompileUnit(language: DW_LANG_C_plus_plus, file: !1, producer: "clang version 20.0.0git", isOptimized: true, runtimeVersion: 0, emissionKind: FullDebug, enums: !2, retainedTypes: !2, imports: !2, splitDebugInlining: false, nameTableKind: None)
!1 = !DIFile(filename: "test.cpp", directory: "/tmp")
!2 = !{}
!3 = !{i32 2, !"Debug Info Version", i32 3}
!4 = !DILocation(line: 206, column: 52, scope: !5)
!5 = distinct !DISubprogram(name: "_build_sub_tree", linkageName: "_ZN9btBvhTree15_build_sub_treeER18GIM_BVH_DATA_ARRAYii", scope: !0, file: !1, line: 160, type: !6, scopeLine: 161, spFlags: DISPFlagDefinition, unit: !0, retainedNodes: !2)
!6 = distinct !DISubroutineType(types: !7)
!7 = !{null}
;.
; CHECK: [[META0:![0-9]+]] = distinct !DICompileUnit(language: DW_LANG_C_plus_plus, file: [[META1:![0-9]+]], producer: "{{.*}}clang version {{.*}}", isOptimized: true, runtimeVersion: 0, emissionKind: FullDebug, enums: [[META2:![0-9]+]], retainedTypes: [[META2]], imports: [[META2]], splitDebugInlining: false, nameTableKind: None)
; CHECK: [[META1]] = !DIFile(filename: "test.cpp", directory: {{.*}})
; CHECK: [[META2]] = !{}
; CHECK: [[DBG4]] = !DILocation(line: 206, column: 52, scope: [[META5:![0-9]+]])
; CHECK: [[META5]] = distinct !DISubprogram(name: "_build_sub_tree", linkageName: "_ZN9btBvhTree15_build_sub_treeER18GIM_BVH_DATA_ARRAYii", scope: [[META0]], file: [[META1]], line: 160, type: [[META6:![0-9]+]], scopeLine: 161, spFlags: DISPFlagDefinition, unit: [[META0]], retainedNodes: [[META2]])
; CHECK: [[META6]] = distinct !DISubroutineType(types: [[META7:![0-9]+]])
; CHECK: [[META7]] = !{null}
;.
